### ISSUE TITLE
Stream machine allow multi consumer

### ISSUE THREAD

**Issue by tangkhaiphuong-colpal** [cedalo/streamsheets#31]
## Summary
I use streamsheets to process the IoT data combine 2 consumer from
- MQTT Consumer
- Rest Consumer

When create the streamsheets, I only select ONE consumer so how to resolve this case. I need data from both 2 Consumer and calculate to publish many producer.

So how to resolve this case?

**Comment by evlach** [comment]
You are right, there is no way currently to have more than one consumer per streamsheet. However it is possible to have more than 1 sheet per machine. In this way you can have 1 consumer per sheet and you can reference cells from one sheet to the other. This should solve your problem for now but we might consider again if it would be better to allow more consumers per inbox. Of course if you are using say mqtt you could subscribe to multiple topics using one consumer.
