### ISSUE TITLE
created，and immediately exited.

### ISSUE THREAD

**Issue by quanwenbo** [cedalo/streamsheets#40]
### Question

...
CONTAINER ID        IMAGE                                               COMMAND                  CREATED             STATUS                     PORTS                                            NAMES
69fd04dfc365        cedalo/streamsheets-installer:1.6-milestone-linux   "/install /bin/bash"     6 seconds ago       Exited (0) 4 seconds ago                                                    streamsheets

### Context

docker log:

bob@ubuntu:~$ docker logs streamsheets
--> Installing Streamsheets
--> Successfully installed Streamsheets

...

**Comment by cleancoderocker** [comment]
As discussed in our forum you need to first run the installer and then start Streamsheets: https://forum.streamsheets.com/t/docker-install-failed-exit-0-inmediately/143
