### ISSUE TITLE
 How to specify the time zone of the arrivaltime

### ISSUE THREAD

**Issue by kevin100702** [cedalo/streamsheets#41]
### Question

 How to specify the time zone of the arrivaltime？
### Context

 How to specify the time zone of the arrivaltime？

**Comment by Philipp-Struss** [comment]
Hi Kevin,

per default the time zone is always UTC.
However, you can manipulate that fairly easily though formula-operations.
This forum post might do the trick already: [https://forum.cedalo.com/t/mqtt-time-stamp/147]

Let us know whether that helped and answered your question.

**Comment by kevin100702** [comment]
Thanks! Solved my problem

**Comment by Philipp-Struss** [comment]
Brilliant!
