### ISSUE TITLE
How to use the REQUEST function to write data into the InfluxDB 

### ISSUE THREAD

**Issue by jeanfliu** [cedalo/streamsheets#42]
### Question

I tried to use HTTP.REQUEST function to insert data into InfluxDB, but I got a `#INVALID_PARAM_6` message. If the `Body` of the HTTP.REQUEST (POST) could only be in JSON format?

### Context

First, I could really connect to my DB and got all databases correctly. (As shown in the figure below)

![image](https://user-images.githubusercontent.com/17763012/87913413-ada46900-caa1-11ea-8737-a10e25cab6a0.png)

Then, I had a sample string in `B25` as my body, and it would get  a `#INVALID_PARAM_6` message.

![image](https://user-images.githubusercontent.com/17763012/87917199-2bb73e80-caa7-11ea-9eee-b9cd5586a5e8.png)

However, If I turned to take `JSON(A25:B25)` as the body, the `#INVALID_PARAM_6` would not exist. But it would show 

> unable to parse '{"body":"weather,region=us-west temp=64.8"}': invalid number

 error message as below.

![image](https://user-images.githubusercontent.com/17763012/87917219-3376e300-caa7-11ea-97d9-10af19f1c6d6.png)

**Comment by TizianCedalo** [comment]
Hey jeanfliu,

To use Influx properly you will need a different function. The REQUEST() function offers more variety. 
We have an Influx example in our [documentation](https://docs.cedalo.com/tutorials/examples.html#influxdb). 
I hope this helps you.

**Comment by jeanfliu** [comment]
Hi TizianCedalo,

Using the REQUEST() function solved my problem. 😄 
Thanks a lot！
